### ISSUE TITLE
Include illustration and explanation please?

### ISSUE THREAD

**Issue by Naereen** [gerdyw/intxor#1]
Hi,
Could you add a README.md containing some explanations about what the script does, how to run it etc, as well as illustration(s) or figures?
Also, [choosing a license](https://choosealicense.com/) could be useful, if someone wants to use this code (otherwise, as long as you don't specify a license, your code is not open source - [copyright is the default](https://choosealicense.com/no-permission/)).
Thanks!

**Comment by gerdyw** [comment]
Thanks for the comment, let me know if I can improve the readme in any way.

**Comment by Naereen** [comment]
Hi,
Thanks for your quick reply! It seems alright, thanks!
Regards
